kind: pipeline
type: docker
name: springappemp-ci-cd

steps:
  - name: build-springboot-app
    image: maven:latest
    commands:
      - echo "Building Spring Boot application with Maven..."
      - mvn clean package -DskipTests

  - name: deploy-using-docker-compose
    image: docker/compose:1.29.2
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
    commands:
      - echo "Starting services with Docker Compose..."
      - docker-compose up -d --build

volumes:
  - name: docker_socket
    host:
      path: /var/run/docker.sock
