kind: pipeline
type: docker
name: build-and-deploy

steps:
  - name: build-jar
    image: maven:3.8.7-openjdk-17
    commands:
      - mvn clean package -DskipTests

  - name: build-docker-image
    image: plugins/docker
    settings:
      repo: maheshgowdamg25/springappemp
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: run-docker-compose
    image: docker:20.10.24-dind
    privileged: true
    environment:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_TLS_CERTDIR: ""
    commands:
      - apk add --no-cache docker-compose
      - dockerd-entrypoint.sh & sleep 20
      - docker-compose down || true
      - docker-compose up -d
