kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: docker
    commands:
      - docker build -t myapp:latest .

  - name: deploy
    image: docker
    commands:
      
      - docker-compose up -d
