kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: alpine
    commands:
      - echo "Starting build..."
      - echo "Running tests or build commands here"
      - echo "Build complete!"
