kind: pipeline
type: docker
name: deploy

steps:
  - name: build and deploy
    image: docker/compose:latest
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: workspace
        path: /workspace
    working_dir: /workspace
    commands:
      - docker-compose build springapp     # build only the springapp service image
      - docker-compose up -d                # deploy all services in detached mode

volumes:
  dockersock:
    host:
      path: /var/run/docker.sock

  workspace:
    host:
      path: .
