kind: pipeline
type: docker
name: springapp-pipeline

steps:
  - name: setup and test
    image: docker:20.10.16
    environment:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_TLS_CERTDIR: ""
    commands:
      - apk add --no-cache docker-cli docker-compose curl
      - docker-compose up -d
      - sleep 20  # Wait for app to become ready
      - docker-compose ps
      - curl --fail http://localhost:9000/actuator/health || echo "Health check failed"
      - docker-compose down

services:
  - name: docker
    image: docker:dind
    privileged: true
