kind: pipeline
type: docker
name: local-deploy

steps:
  - name: build springapp image
    image: docker
    privileged: true
    commands:
      - docker build -t springapp:latest .

  - name: deploy with docker-compose
    image: docker/compose:latest
    privileged: true
    commands:
      - docker-compose pull
      - docker-compose up -d --build
