kind: pipeline
type: docker
name: springapp-pipeline

steps:
  - name: setup and test
    image: docker/compose:1.29.2
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker-compose up -d
      - sleep 20  # wait for services to be ready
      - docker-compose ps
      # Optional: Add test steps here
      # - curl http://localhost:9000/health
      - docker-compose down

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock
